name: Deploy to GH Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
        env:
          VITE_EPIC_CLIENT_ID: ${{ secrets.VITE_EPIC_CLIENT_ID }}
          VITE_PUBLIC_URL: ${{ secrets.VITE_PUBLIC_URL }}
      - run: npm ci
      - run: npm run build

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
